# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 23, 15, 28, 10, 542691, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
